version: '3.9'

services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=gestao_vagas