version: '3.9'

networks:
  gv-network:
    driver: bridge

volumes:
  prometheus_data:

services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=gestao_vagas
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_data
        target: /prometheus
    networks:
      - gv-network
    ports:
      - 9090:9090
