version: '3.9'

services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gestao_vagas